(function(){
'use strict';
const VERSION='2026.07.20-V17-RULE-ENGINE';
const jsonCache={};
async function loadJson(path){if(!jsonCache[path]){const r=await fetch(path+'?v=17',{cache:'no-store'});if(!r.ok)throw new Error(path+' 讀取失敗');jsonCache[path]=await r.json()}return jsonCache[path]}
const get=id=>document.getElementById(id), val=id=>get(id)?String(get(id).value||'').trim():'', checked=id=>!!get(id)?.checked;
function setPath(root,path,value){const keys=path.split('.');let p=root;keys.slice(0,-1).forEach(k=>p=p[k]||(p[k]={}));p[keys.at(-1)]=value}
function modelFromForm(){
  const model={schemaVersion:'17.0.0',case:{},amount:{},procedure:{},security:{},agreement:{},review:{},meta:{generatedAt:new Date().toISOString(),version:VERSION}};
  const values={caseName:val('caseName'),agency:val('agency'),need:val('need'),type:val('type'),budget:Number(val('budget')||0),expansionAmount:Number(val('expansionAmount')||0),tenderMethod:val('tenderMethod'),tenderBasis:val('tenderBasis'),restrictedProcedure:val('restrictedProcedure'),award:val('award'),jointTender:val('jointTender'),basePrice:val('basePrice'),noBasePriceReason:val('noBasePriceReason'),bidBond:val('bidBond'),performanceBond:val('performanceBond'),gpa:checked('gpa'),anztec:checked('anztec'),astEP:checked('astEP'),sensitiveIT:val('sensitiveIT'),nationalSecurity:val('nationalSecurity'),budgetPublishedReview:val('budgetPublishedReview')};
  const map={caseName:'case.name',agency:'case.agency',need:'case.need',type:'case.procurementType',budget:'amount.budget',expansionAmount:'amount.expansion',tenderMethod:'procedure.tenderMethod',tenderBasis:'procedure.legalBasis',restrictedProcedure:'procedure.restrictedProcedure',award:'procedure.awardMethod',jointTender:'procedure.jointTender',basePrice:'procedure.basePrice',noBasePriceReason:'procedure.noBasePriceReason',bidBond:'security.bidBond',performanceBond:'security.performanceBond',gpa:'agreement.gpa',anztec:'agreement.anztec',astEP:'agreement.astEP',sensitiveIT:'security.sensitiveIT',nationalSecurity:'security.nationalSecurity',budgetPublishedReview:'review.budgetPublished'};
  Object.entries(map).forEach(([k,p])=>setPath(model,p,values[k]));model.amount.total=model.amount.budget+model.amount.expansion;return model
}
function tierFor(model,legal){const n=model.amount.total,t=model.case.procurementType,x=legal.thresholds;if(n<=x.small)return {id:'tier1',label:'公告金額十分之一以下',item:'4.1'};if(n<x.announcement)return {id:'tier2',label:'逾公告金額十分之一未達公告金額',item:'4.2'};if(n<x.review[t])return {id:'tier3',label:'公告金額以上未達查核金額',item:'4.3'};if(n<x.large[t])return {id:'tier4',label:'查核金額以上未達巨額',item:'4.4'};return {id:'tier5',label:'巨額採購',item:'4.5'}}
function committeeFor(agency,legal){const hit=Object.keys(legal.complaintCommittees).find(k=>k!=='central'&&agency.includes(k));return hit?{key:hit,label:legal.complaintCommittees[hit],review:false}:{key:'central',label:legal.complaintCommittees.central,review:!agency}}
function decisions(model,legal){
  const tier=tierFor(model,legal),committee=committeeFor(model.case.agency,legal),d={tier,committee,selections:{},reviews:[],blocks:[]},s=d.selections;
  s[3]=[{'工程採購':'3.1','財物採購':'3.2','勞務採購':'3.3'}[model.case.procurementType]];s[4]=[tier.item];if(tier.id==='tier5')s[4].push('4.largeAnalysis');s[5]=['5.2'];s[13]=['13.'+committee.key];s[14]=['14.1'];
  const tm=model.procedure.tenderMethod;s[15]=tm==='open'?['15.1']:tm==='selective'?['15.2']:tm==='restricted'?['15.3']:[];if(['selective','restricted'].includes(tm)&&['','unknown'].includes(model.procedure.legalBasis)){d.blocks.push('招標方式的法規款次尚未確認。')}
  const treaties=['gpa','anztec','astEP'].filter(k=>model.agreement[k]);s[16]=treaties.length?['16.1',...treaties.map(x=>'16.1.'+x)]:['16.2','16.2.noForeign'];
  if(/統包/.test(model.case.need)){s[17]=[];d.reviews.push('需求內容出現「統包」，第17點須由採購人員確認。')}else s[17]=['17.2'];
  const jt=model.procedure.jointTender;s[18]=jt.startsWith('yes-')?['18.1','18.limit.'+jt.split('-')[1]]:jt==='no'?['18.2']:[];if(!s[18].length)d.reviews.push('第18點共同投標尚待確認。');
  Object.assign(s,{19:['19.written'],22:['22.noCorrection'],23:['23.noAlternative'],24:['24.60days'],25:['25.oneCopy'],26:['26.traditionalChinese']});
  s[31]=tm==='open'&&model.procedure.awardMethod==='scored-lowest'?['31.staged','31.qualificationFirst']:['31.notStaged'];
  const service=model.case.procurementType==='勞務採購',bidNo=model.security.bidBond==='no'||(model.security.bidBond==='auto'&&service),perfNo=model.security.performanceBond==='no'||(model.security.performanceBond==='auto'&&service);
  s[32]=bidNo?['32.noBond']:['32.collect'];s[38]=bidNo&&service?['38.serviceReason']:[];s[39]=perfNo?['39.noBond']:['39.collect'];s[44]=perfNo&&service?['44.serviceReason']:[];
  if(bidNo&&!s[38].length)d.blocks.push('不收押標金，但第38點沒有可確定的免收理由。');if(perfNo&&!s[44].length)d.blocks.push('不收履約保證金，但第44點沒有可確定的免收理由。');
  const bp=model.procedure.basePrice;s[57]=bp==='private'?['57.1']:bp==='public'?['57.2']:bp==='none'?['57.3','57.reason.'+model.procedure.noBasePriceReason]:[];if(!s[57].length||bp==='none'&&['','unknown'].includes(model.procedure.noBasePriceReason))d.blocks.push('第57點底價或不訂底價理由尚未確認。');
  const am=model.procedure.awardMethod,awardMap={lowest:['58.1','58.1.1'],'scored-lowest':['58.1','58.1.2'],'most-advantageous':['58.2','58.2.1'],'quasi-most-advantageous':['58.2','58.2.2'],'reference-most-advantageous':['58.2','58.2.3'],highest:['58.3']};s[58]=awardMap[am]||[];
  if(am==='reference-most-advantageous'&&model.amount.total>=legal.thresholds.announcement)d.blocks.push('公告金額以上案件不得採參考最有利標精神。');if(am==='quasi-most-advantageous'&&tm!=='restricted')d.blocks.push('準用最有利標必須配合限制性招標及法定款次。');
  Object.assign(s,{59:['59.nonMultiple'],61:['61.noNegotiation'],63:['63.noException'],74:['74.TWD'],78:['78.writtenContract']});s[64]=[];if(model.security.sensitiveIT==='yes')s[64].push('64.sensitiveIT');if(model.security.nationalSecurity==='yes')s[64].push('64.excludeChinaCapital');if(['unknown',''].includes(model.security.nationalSecurity))d.reviews.push('第64點國安排除條款尚待確認。');s[67]=model.review.budgetPublished==='yes'?['67.overPublishedBudgetDisqualified']:[];if(model.review.budgetPublished==='unknown')d.reviews.push('第67點是否公告預算尚待採購人員確認。');if(committee.review)d.reviews.push('第13點申訴審議機關因機關名稱未填，暫採中央主管機關並須確認。');return d
}
function checkLine(text,needle){const escaped=needle.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return text.replace(new RegExp('(^[ \\t]*)☐('+escaped+')','m'),(m,a,b)=>a+'☑'+b)}
function section(text,start,next,fn){const re=new RegExp('(^[ \\t]*'+start+'、[\\s\\S]*?)(?=^[ \\t]*'+next+'、)','m');return text.replace(re,b=>fn(b))}
function applyNotice(raw,model,d){
  let t=raw.replace(/^\uFEFF/,'').replace(/[■☒□█]/g,'☐');
  t=t.replace(/(二、\s*本標案名稱：)[^\n]*/,`$1${model.case.name}`);
  const typeText={'工程採購':'(1)工程。','財物採購':'(2)財物；其性質為：','勞務採購':'(3)勞務。'}[model.case.procurementType];if(typeText)t=checkLine(t,typeText);
  const tierText={'tier1':'(1)公告金額十分之一以下之採購。','tier2':'(2)逾公告金額十分之一未達公告金額之採購。','tier3':'(3)公告金額以上未達查核金額之採購。','tier4':'(4)查核金額以上未達巨額之採購。','tier5':'(5)巨額採購。'}[d.tier.id];t=checkLine(t,tierText);if(d.tier.id==='tier5')t=checkLine(t,'已依「機關提報巨額採購使用情形及效益分析作業規定」第2點第1項，簽准預期使用情形及效益目標。');
  t=checkLine(t,'(2)非共同供應契約。').replace('☐採購法主管機關設立之採購申訴審議委員會','☑行政院公共工程委員會採購申訴審議委員會');if(d.committee.key!=='central')t=t.replace('☐'+d.committee.label,'☑'+d.committee.label).replace('☑行政院公共工程委員會採購申訴審議委員會','☐行政院公共工程委員會採購申訴審議委員會');t=checkLine(t,'(1)未分批辦理。');
  t=section(t,'十五','十六',b=>{const m=model.procedure.tenderMethod,basis=model.procedure.legalBasis,proc=model.procedure.restrictedProcedure;if(m==='open')b=checkLine(b,'(1)公開招標');if(m==='selective'){b=checkLine(b,'(2)選擇性招標：符合採購法第20條');const c=basis.match(/^20-(\d)/)?.[1];if(c)b=b.replace('☐第'+c+'款','☑第'+c+'款')}if(m==='restricted'){b=checkLine(b,'(3)限制性招標：本案業經需求、使用或承辦採購單位敘明符合採購法第22條第1項第     款之情形，並簽報機關首長或其授權人員核准採限制性招標。');const c=basis.match(/^22-(\d+)/)?.[1];if(c)b=b.replace('第     款之情形','第'+c+'款之情形');if(proc==='public-evaluation'){b=checkLine(b,'（3-1）公開評選、公開勘選優勝廠商：');if(basis.startsWith('22-9')){b=checkLine(b,'（3-1-1）依採購法第22條第1項第9款辦理；');const x={'22-9-professional':'委託專業服務','22-9-technical':'委託技術服務','22-9-information':'委託資訊服務','22-9-social':'委託社會福利服務'}[basis];if(x)b=b.replace('☐'+x,'☑'+x)}if(basis==='22-10')b=checkLine(b,'（3-1-2）依採購法第22條第1項第10款辦理。');if(basis==='22-11')b=checkLine(b,'（3-1-3）依採購法第22條第1項第11款辦理。')}if(proc==='compare')b=checkLine(b,'（3-2）比價；');if(proc==='negotiate')b=checkLine(b,'（3-3）議價；');if(proc==='public-solicitation')b=b.replace('☐（3-4）依採購法第22條第1項第____款辦理','☑（3-4）依採購法第22條第1項第'+(c||'____')+'款辦理')}return b});
  t=section(t,'十六','十七',b=>{const any=model.agreement.gpa||model.agreement.anztec||model.agreement.astEP;if(any){b=checkLine(b,'(1)適用我國締結之條約或協定；其名稱為：');if(model.agreement.gpa)b=checkLine(b,'世界貿易組織政府採購協定（GPA）。');if(model.agreement.anztec)b=checkLine(b,'臺紐經濟合作協定。');if(model.agreement.astEP)b=checkLine(b,'臺星經濟夥伴協定。')}else{b=checkLine(b,'(2)不適用我國締結之條約或協定，外國廠商：');b=checkLine(b,'不可參與投標。我國廠商所供應標的（含工程、財物及勞務）之原產地須屬我國者。')}return b});
  if(!/統包/.test(model.case.need))t=checkLine(t,'(2)非以統包辦理招標。');const jt=model.procedure.jointTender;if(jt==='no')t=checkLine(t,'(2)不允許廠商共同投標。');else if(jt.startsWith('yes-')){t=checkLine(t,'(1)依採購法第25條規定允許廠商共同投標，其家數上限為');t=t.replace('☐'+jt.split('-')[1]+'家','☑'+jt.split('-')[1]+'家')}
  t=checkLine(t,'（1）以書面方式投標。');t=checkLine(t,'(2)不允許廠商於開標前補正非契約必要之點之文件。');t=checkLine(t,'(2)不允許提出替代方案。');t=t.replace('投標文件有效期：自投標時起至開標後______日止。','投標文件有效期：自投標時起至開標後60日止。');t=checkLine(t,'(1)1式1份。');t=checkLine(t,'(2)中文(正體字)，但特殊技術或材料之圖文資料得使用英文。');
  if(model.procedure.tenderMethod==='open'&&model.procedure.awardMethod==='scored-lowest'){t=checkLine(t,'(2)分段開標（請勾選項目）；投標廠商應就各段標之標封分別裝封並標示內含資格標、規格標或價格標等：');t=checkLine(t,'公開招標，資格、規格與價格一次投標分段開標。')}else t=checkLine(t,'(1)不分段開標。所有投標文件置於一標封內，不必按文件屬性分別裝封。');
  if(d.selections[38].length)t=section(t,'三十八','三十九',b=>checkLine(b,'(1)勞務採購。'));if(d.selections[44].length)t=section(t,'四十四','四十五',b=>checkLine(b,'(1)勞務採購。'));
  t=section(t,'五十七','五十八',b=>{const x=model.procedure.basePrice;if(x==='private')b=checkLine(b,'(1)訂底價，但不公告底價。');if(x==='public')b=checkLine(b,'(2)訂底價，並公告底價。');if(x==='none'){b=checkLine(b,'(3)不訂底價，理由為：');const label={complex:'訂定底價確有困難之特殊或複雜案件', 'most-advantageous':'以最有利標決標之採購',professional:'專業服務、技術服務、資訊服務、社會福利服務或文化創意服務者，以不訂底價之最有利標',small:'小額採購'}[model.procedure.noBasePriceReason];if(label)b=b.replace('☐'+label,'☑'+label)}return b});
  t=section(t,'五十八','五十九',b=>{const a=model.procedure.awardMethod;if(['lowest','scored-lowest'].includes(a))b=checkLine(b,'(1)最低標：');if(a==='lowest')b=checkLine(b,'（1-1）非依採購法施行細則第64條之2辦理。');if(a==='scored-lowest')b=checkLine(b,'（1-2）依採購法施行細則第64條之2採評分及格最低標');if(['most-advantageous','quasi-most-advantageous','reference-most-advantageous'].includes(a))b=checkLine(b,'(2)最有利標');if(a==='most-advantageous')b=checkLine(b,'（2-1）依採購法第56條適用最有利標');if(a==='quasi-most-advantageous')b=checkLine(b,'（2-2）依採購法第22條第1項');if(a==='reference-most-advantageous')b=checkLine(b,'（2-3）未達公告金額之採購參考最有利標精神');if(a==='highest')b=checkLine(b,'(3)最高標。');return b});
  t=checkLine(t,'(1)非複數決標。');t=checkLine(t,'(2)否。');t=checkLine(t,'(1)無例外情形。');if(model.security.sensitiveIT==='yes')t=checkLine(t,'本採購屬經濟部(投資審議司)公告「具敏感性或國安(含資安)疑慮之業務範疇」之資訊服務採購，廠商不得為大陸地區廠商、第三地區含陸資成分廠商及經濟部(投資審議司)公告之陸資資訊服務業者。');if(model.security.nationalSecurity==='yes')t=checkLine(t,'本採購內容涉及國家安全，不允許大陸地區廠商、第三地區含陸資成分廠商及在臺陸資廠商參與。');if(model.review.budgetPublished==='yes')t=checkLine(t,'(1)高於公告之預算者。');t=checkLine(t,'(1)新臺幣。');t=checkLine(t,'以書面文件簽約。');return t
}
function decisionHtml(d){const rows=[4,13,15,16,17,18,31,32,38,39,44,57,58,64,67].map(n=>`<tr><td>第${n}點</td><td>${(d.selections[n]||[]).join('、')||'未勾選'}</td></tr>`).join('');return `<h3>V17 規則引擎判斷紀錄</h3><table style="width:100%;border-collapse:collapse"><tr><th style="border:1px solid #bbb;padding:7px">項次</th><th style="border:1px solid #bbb;padding:7px">勾選代碼</th></tr>${rows.replaceAll('<td>','<td style="border:1px solid #bbb;padding:7px">')}</table>`}
function resetCase(){if(!confirm('確定清除目前案件並建立新案件嗎？'))return;document.querySelectorAll('#intake input,#intake textarea').forEach(el=>{if(el.type==='checkbox')el.checked=false;else el.value=''});const defaults={type:'勞務採購',expansionAmount:'0',tenderMethod:'open',award:'lowest',jointTender:'no',basePrice:'private',bidBond:'auto',performanceBond:'auto',sensitiveIT:'no',nationalSecurity:'no',periodMode:'relative',periodStartEvent:'awardNextDay',periodDuration:'90',periodUnit:'calendarDay'};Object.entries(defaults).forEach(([id,v])=>{if(get(id))get(id).value=v});docs={};selectedOfficial=[];sessionStorage.removeItem('v17-last-case');sessionStorage.removeItem('v17-last-decision');updateProcurementAmount();updateTenderBasis();updateIntakeOptions();if(window.V171Period)V171Period.update();get('sideCase').textContent='新採購案件';go('intake');toast('已清除舊案件資料')}
async function loadFullTenderNoticeV17(d,src){const [raw,legal]=await Promise.all([fetch('data/tender-notice-1141231.txt?v=17',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('完整投標須知母版讀取失敗');return r.text()}),loadJson('data/legal-parameters.json')]);const model=modelFromForm(),result=decisions(model,legal),text=applyNotice(raw,model,result);sessionStorage.setItem('v17-last-case',JSON.stringify(model));sessionStorage.setItem('v17-last-decision',JSON.stringify(result));const sources='<a href="https://www.pcc.gov.tw/content/list?eid=9807&lang=1" target="_blank" rel="noopener">工程會官方範本來源</a>';return `<h2>${escapeHtml(model.case.name)}<br>投標須知</h2><p>${src}</p><div class="notice"><b>V17 規則引擎：</b>採購金額 ${money(model.amount.total)}，判定「${result.tier.label}」。${result.blocks.length?'<br><b>重大衝突：</b>'+result.blocks.map(escapeHtml).join('；'):'未發現阻擋性衝突。'}${result.reviews.length?'<br><b>人工確認：</b>'+result.reviews.map(escapeHtml).join('；'):''}</div><div class="source-meta">規則版本：${VERSION}｜母版：114.12.31｜${sources}</div>${decisionHtml(result)}<h3>工程會投標須知範本全文（依案件勾選）</h3><div class="official-fulltext">${escapeHtml(text)}</div>${foot()}`}
async function refreshConfirm(){const legal=await loadJson('data/legal-parameters.json'),model=modelFromForm(),d=decisions(model,legal),box=get('prechecks');if(!box)return;box.innerHTML=[...d.blocks.map(x=>`<div class="check"><span class="dot danger"></span><div><b>阻擋生成</b><p>${escapeHtml(x)}</p></div></div>`),...d.reviews.map(x=>`<div class="check"><span class="dot warn"></span><div><b>待人工確認</b><p>${escapeHtml(x)}</p></div></div>`),`<div class="check"><span class="dot ok"></span><div><b>採購級距</b><p>${escapeHtml(d.tier.label)}；第4點僅勾選 ${d.tier.item}。</p></div></div>`,`<div class="check"><span class="dot ok"></span><div><b>申訴審議機關</b><p>${escapeHtml(d.committee.label)}</p></div></div>`].join('');return {model,d}}
const oldPrepare=window.prepareSummary;window.prepareSummary=async function(){oldPrepare();if(document.getElementById('confirm').classList.contains('active'))await refreshConfirm()};const oldGenerate=window.generateDocs;window.loadFullTenderNotice=loadFullTenderNoticeV17;window.generateDocs=async function(){const state=await refreshConfirm();if(state?.d.blocks.length){toast('有重大衝突，請先在03階段修正');go('confirm');return}await oldGenerate();};
window.V17Engine={VERSION,modelFromForm,tierFor,committeeFor,decisions,applyNotice,loadJson,refreshConfirm,resetCase};document.querySelector('.privacy').innerHTML='本原型僅供流程展示<br>AI 建議須由權責人員確認後使用<br>版本：'+VERSION;
})();
